# 通过 Github actions， 在 Github 仓库的每一次 commit 后自动同步到 Gitee 上
name: Sync to Gitee
on:
  push:
    branches:
      - main
  # 可手动操控
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出GitHub仓库代码
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取完整提交历史

      # 步骤2：配置SSH密钥
      - name: Setup SSH
        env:
          GITEE_SSH_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$GITEE_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "actions@github.com"

      # 步骤3：强制镜像到Gitee
      - name: Mirror to Gitee
        env:
          GITEE_USER: ${{ secrets.GITEE_USER }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          LOWER_REPO=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          echo "Original: $REPO_NAME → Lowercase: $LOWER_REPO"
          git remote add gitee git@gitee.com:$GITEE_USER/$LOWER_REPO.git
          git push --force --mirror gitee